### ISSUE TITLE
It errors after update 1.2.16

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [strike-digital/node_pie#18]
Blender3.6.1

(3.0 is the path of addon not the blender version. I use 3.6)

```
Traceback (most recent call last):
  File "G:\blender\36\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "G:\blenderplus\3.0\addons\node_pie\__init__.py", line 28, in <module>
    auto_load.init()
  File "G:\blenderplus\3.0\addons\node_pie\auto_load.py", line 24, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "G:\blenderplus\3.0\addons\node_pie\auto_load.py", line 62, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "G:\blenderplus\3.0\addons\node_pie\auto_load.py", line 67, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "G:\blender\36\3.6\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\blenderplus\3.0\addons\node_pie\node_pie\npie_operators.py", line 12, in <module>
    from .npie_helpers import BOperator, get_all_def_files
ImportError: cannot import name 'BOperator' from 'node_pie.node_pie.npie_helpers' (G:\blenderplus\3.0\addons\node_pie\node_pie\npie_helpers.py)
```

**Comment by strike-digital** [comment]
Hi, just to make sure, it seems like that's from an old version of node pie, so if the problem is still there, you could try removing it in the blender preferences, and then reinstalling the latest version
